### ISSUE TITLE
APC broken in the latest 1.92.0 vscode stable

### ISSUE THREAD

**Issue by jatindotdev** [drcika/apc-extension#206] opened 2024-08-01 18:05 UTC
@drcika looks like they did some file renaming internally

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/2481d432-df23-41ec-bb88-ee3a250e8460">

```
Version: 1.92.0
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

**Comment by edgardluz** [comment] 2024-08-01 18:13
same issue

**Comment by ashish0kumar** [comment] 2024-08-01 18:19
Encountering same issue

**Comment by KhoaLee** [comment] 2024-08-01 18:27
Encounter same issue too

**Comment by ian-h-chamberlain** [comment] 2024-08-01 18:32
FWIW, not sure if anything else changed (or if other OSes would have different filenames) but it looks like there is a file named `bootstrap-fork.js` in that directory:
```console
$ ls /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/
total 2336
drwxr-xr-x@  9 ichamberlain  staff   288B Aug  1 03:13 ./
drwxr-xr-x@ 14 ichamberlain  staff   448B Aug  1 03:13 ../
-rw-r--r--@  1 ichamberlain  staff    48K Aug  1 02:25 bootstrap-fork.js
-rw-r--r--@  1 ichamberlain  staff    48K Aug  1 02:25 cli.js
-rw-r--r--@  1 ichamberlain  staff    60K Aug  1 02:25 main.js
-rw-r--r--@  1 ichamberlain  staff   385K Aug  1 03:03 nls.keys.json
-rw-r--r--@  1 ichamberlain  staff   619K Aug  1 03:03 nls.messages.json
drwxr-xr-x@  7 ichamberlain  staff   224B Aug  1 03:13 vs/
drwxr-xr-x@  3 ichamberlain  staff    96B Aug  1 03:13 vscode-dts/
```

**Comment by jatindotdev** [comment] 2024-08-01 18:42
@ian-h-chamberlain you are right

```sh
~ ❱ /bin/ls -la /Users/jatin/Downloads/Visual\ Studio\ Code.app/Contents/Resources/app/out/
total 2832
drwxr-xr-x@ 12 jatin  admin      384 Jul 10 10:37 .
drwxr-xr-x@ 14 jatin  admin      448 Jul 10 10:38 ..
-rw-r--r--@  1 jatin  admin     1376 Jul 10 09:50 bootstrap-amd.js
-rw-r--r--@  1 jatin  admin     2866 Jul 10 09:50 bootstrap-fork.js
-rw-r--r--@  1 jatin  admin     1835 Jul 10 09:50 bootstrap-node.js
-rw-r--r--@  1 jatin  admin     3707 Jul 10 09:50 bootstrap-window.js
-rw-r--r--@  1 jatin  admin     2467 Jul 10 09:50 bootstrap.js
-rw-r--r--@  1 jatin  admin    40219 Jul 10 09:50 cli.js
-rw-r--r--@  1 jatin  admin    55468 Jul 10 09:50 main.js
-rw-r--r--@  1 jatin  admin  1330671 Jul 10 10:29 nls.metadata.json
drwxr-xr-x@  8 jatin  admin      256 Jul 10 10:37 vs
drwxr-xr-x@  3 jatin  admin       96 Jul 10 10:37 vscode-dts
```

earlier we used to have multiple verisons of bootstrap files now we have one

**Comment by AmoabaKelvin** [comment] 2024-08-01 19:11
Encountering the same issue

**Comment by iagobruno** [comment] 2024-08-01 19:11
Same issue :(

**Comment by pivoshenko** [comment] 2024-08-01 19:27
Damn same issue 🥺

**Comment by darianmorat** [comment] 2024-08-01 19:29
Same issue... btw, don't even think in creating the file in that route or your vs code is gonna break completely

**Comment by strFelix** [comment] 2024-08-01 19:37
same inssue here 😢

**Comment by arthvm** [comment] 2024-08-01 19:45
Same issue here.

I've encountered this problem a few months ago while using Insiders. There are two open issues on this topic already, one from a month ago (#203) and another one from June (#198), but no one found a fix yet.

**Comment by epulla** [comment] 2024-08-01 20:04
same issue here :( I'm using VsCode installed via `brew`

**Comment by m4dd0c** [comment] 2024-08-01 20:28
no workaround yet :( I just got to know about this extension. loved it but now im in grief.

**Comment by henrythierrydev** [comment] 2024-08-01 20:48
same

**Comment by steveulfelder** [comment] 2024-08-01 21:34
## Downgrade VS code to fix APC

Pick the method corresponding to how you installed VS code. **Once you've downgraded go to preferences, search 'update', and set `Update: Mode` to `none`**

### Manual install (browser download)

1. Download the previous major version (1.91) from [here](https://code.visualstudio.com/updates/v1_91)
1. Overwrite your current install (extensions and settings will be preserved)

### Homebrew install

~~1. `brew install visual-studio-code@1.91.1`~~
1. Download the 1.91.1 cask file from [here](https://github.com/Homebrew/homebrew-cask/blob/506e9abc71c30c294d4dfb139245646060f89a3e/Casks/v/visual-studio-code.rb)
1. Navigate to the folder the file was downloaded to
1. `brew install --cask ./visual-studio-code.rb`

### Linux Microsoft repo install

1. Use your package manager to downgrade to the last `1.91.x` version. i.e.:
```
apt remove code
apt autoremove
apt install code=1.91.1
```

**Comment by Ender-Wang** [comment] 2024-08-01 21:54
- You can download the previous version here: [https://code.visualstudio.com/updates/v1_91](https://code.visualstudio.com/updates/v1_91), I rolled back without problem. 
- I installed vscode via brew, so be sure to firstly update to 1.92 in brew (and it's live in brew ATM) so vscode is up-to-date to brew, then download the previous version to replace it.
- Donot forget to set Update mode in vscode to non-auto update mode.

**Comment by Ender-Wang** [comment] 2024-08-01 21:57
> ## Downgrade VS code to fix APC
> Pick the method corresponding to how you installed VS code. **Once you've downgraded go to preferences, search 'update', and set `Update: Mode` to `none`**
> 
> ### Manual install (browser download)
> 1. Download the previous major version (1.91) from [here](https://code.visualstudio.com/updates/v1_91)
> 2. Overwrite your current install (extensions and settings will be preserved)
> 
> ### Homebrew install
> 1. `brew install visual-studio-code@1.91.1`
> 
> ### Linux Microsoft repo install
> 1. Use your package manager to downgrade to the last `1.91.x` version. i.e.:
> 
> ```
> apt remove code
> apt autoremove
> apt install code=1.91.1
> ```

Actually you cannot do it via `brew install visual-studio-code@1.91.1`, and just tested it got error 
```
brew install visual-studio-code@1.91.1
Warning: No available formula with the name "visual-studio-code@1.91.1".
==> Searching for similarly named formulae and casks...
==> Casks
visual-studio-code ✔

To install visual-studio-code ✔, run:
  brew install --cask visual-studio-code ✔
```
Check out my reply above, it worked for me :D

**Comment by forivall** [comment] 2024-08-01 23:01
I think these are relevant vscode changes:  https://github.com/microsoft/vscode/pull/214588 https://github.com/microsoft/vscode/pull/219265 https://github.com/microsoft/vscode/pull/219841 https://github.com/microsoft/vscode/pull/221154

basically, looks like the loader which required `bootstrap-amd.js` has all been reworked so that it's now bundling into the `main.js`, and there's different loading paths based on if the language is english or not (where it'll need to load the localizations), so the current hooking method will need to be revised.

**Comment by iJuulia** [comment] 2024-08-01 23:20
> ## Downgrade VS code to fix APC
> Pick the method corresponding to how you installed VS code. **Once you've downgraded go to preferences, search 'update', and set `Update: Mode` to `none`**
> 
> ### Manual install (browser download)
> 1. Download the previous major version (1.91) from [here](https://code.visualstudio.com/updates/v1_91)
> 2. Overwrite your current install (extensions and settings will be preserved)
> 
> ### Homebrew install
> 1. `brew install visual-studio-code@1.91.1`
> 
> ### Linux Microsoft repo install
> 1. Use your package manager to downgrade to the last `1.91.x` version. i.e.:
> 
> ```
> apt remove code
> apt autoremove
> apt install code=1.91.1
> ```

thank you so much!! it worked :)

**Comment by tamalCodes** [comment] 2024-08-02 03:30
So now we'll be stuck to V 1.91 forever until there's a fix, which seems like ain't happening anytime soon

**Comment by isobarbaric** [comment] 2024-08-02 03:53
same issue haha

**Comment by kalpeshdhotre** [comment] 2024-08-02 04:13
Facing same problem !
@drcika kindly Requesting you to fix as soon as possible.
thank you in advance

**Comment by GoldSept** [comment] 2024-08-02 07:11
lol Same issue

**Comment by emilshr-sigtech** [comment] 2024-08-02 08:09
Upvoting this issue as I'm facing the same problem!

Edit: I've downgraded to `1.91.1` and the extension isn't breaking.

**Comment by MrBns** [comment] 2024-08-02 08:57
Same issue here. after Giving permision `sudo chown -R $(whoami)  /usr/share/code` **Vscode** isnot opening anymore. lol.

**Comment by joaoKuchnir** [comment] 2024-08-02 11:50
> Same issue here. after Giving permision `sudo chown -R $(whoami) /usr/share/code` **Vscode** isnot opening anymore. lol.

Same here!

**Comment by epulla** [comment] 2024-08-02 13:51
yeah, it won't work even if you give permission to the `/usr/share/code` or any installation path because the error is caused by a missing file from the `1.92` vscode version (specifically the `bootstrap-amd.js`.

> FWIW, not sure if anything else changed (or if other OSes would have different filenames) but it looks like there is a file named `bootstrap-fork.js` in that directory:
> 
> ```
> $ ls /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/
> total 2336
> drwxr-xr-x@  9 ichamberlain  staff   288B Aug  1 03:13 ./
> drwxr-xr-x@ 14 ichamberlain  staff   448B Aug  1 03:13 ../
> -rw-r--r--@  1 ichamberlain  staff    48K Aug  1 02:25 bootstrap-fork.js
> -rw-r--r--@  1 ichamberlain  staff    48K Aug  1 02:25 cli.js
> -rw-r--r--@  1 ichamberlain  staff    60K Aug  1 02:25 main.js
> -rw-r--r--@  1 ichamberlain  staff   385K Aug  1 03:03 nls.keys.json
> -rw-r--r--@  1 ichamberlain  staff   619K Aug  1 03:03 nls.messages.json
> drwxr-xr-x@  7 ichamberlain  staff   224B Aug  1 03:13 vs/
> drwxr-xr-x@  3 ichamberlain  staff    96B Aug  1 03:13 vscode-dts/
> ```

**Comment by dir** [comment] 2024-08-02 15:52
I feared this day would come...

**Comment by ghost** [comment] 2024-08-02 16:01
I believe this is a critical level problem, please resolve it as soon as possible

**Comment by pedroalmeida415** [comment] 2024-08-02 17:55
Bad news: https://github.com/drcika/apc-extension/issues/207#issuecomment-2265878623

**Comment by JaviColomo** [comment] 2024-08-02 19:14
Same annoying issue here :(

**Comment by IrishBruse** [comment] 2024-08-02 20:26
Fixed in 0.4.0

**Closed as completed** 2024-08-02 20:48 UTC

**Comment by berrimi** [comment] 2024-08-02 20:52
still after updating to 0.4.0 it won't work

**Comment by drcika** [comment] 2024-08-02 20:56
clear the cache or restart several times

**Comment by berrimi** [comment] 2024-08-02 21:28
i did clear the cache wich include these folders 
Cache
CachedData
CachedExtensions
CachedExtensionVSIXs
Code Cache
i restart the app several times 
i try restarting my pc 
i even reinstall vs code (i am in windows 11)
still does't work

**Comment by JaviColomo** [comment] 2024-08-02 21:33
This worked for me after the extension update to 0.4.0:
- Open command palette.
- Execute "Enable APC". It will show a dialog asking for restart - click OK
- Wait for it to restart and a couple minutes to load and it works.

**Comment by berrimi** [comment] 2024-08-02 21:41
i did execute "Enable APC" but still doesn't work

**Comment by Adriianooo** [comment] 2024-08-02 21:44
I did the same thing and the error does not appear anymore, but it seems that the apc configs did not update

**Comment by berrimi** [comment] 2024-08-02 21:52
yes the error msg is gone but the apc config is not working

**Comment by Adriianooo** [comment] 2024-08-02 21:53
I tried "reload window" now and it worked for me. Try this on your machine and it will probably work.

**Comment by berrimi** [comment] 2024-08-02 22:04
thank you now it work partially it still doesn't load the full config like:
    "titleBarStyle": "hiddenInset",
    "opacity": 0.8
and it requires "reload window" each time i open vs code

**Comment by arthvm** [comment] 2024-08-04 14:42
> thank you now it work partially it still doesn't load the full config like: "titleBarStyle": "hiddenInset", "opacity": 0.8 and it requires "reload window" each time i open vs code

Having the same problem here. For the extension to work I need to "Reload Window" every time

**Comment by 0xWeverton** [comment] 2024-09-10 21:53
its worked for me in cursor

https://github.com/drcika/apc-extension/issues/149#issuecomment-2342073479
