### ISSUE TITLE
Extension Disabled on Update

### ISSUE THREAD

**Issue by AlexvZyl** [drcika/apc-extension#56] opened 2023-08-04 07:03 UTC
When VSCodium automatically updated itself this morning, this extension was disabled for some reason.  In my utter despair I thought VSCode broke something *again*, but luckily I was wrong.

I have absolutely no idea why this happens, but it would probably be better to notify the user when it is disabled or automatically enable it again.

#45

**Comment by jmeistrich** [comment] 2023-08-12 05:04
This just happened to me too, and "Enable Apc extension" fixed it. If you're having trouble reproducing it I'd be happy to enable some logging and try to find a pattern. I had VSCode updates disabled since CustomizeUI broke, so that I could keep my hidden titlebar, so I'm very happy this new extension exists! So I'm happy to help if I can :).

**Comment by drcika** [comment] 2023-08-13 14:24
should be fixed with v0.3.0

**Closed as completed by drcika** 2023-08-13 14:24 UTC
